
package Inicial;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        btnAgoraNao = new javax.swing.JButton();
        lblJaPossuiConta = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastre-se");
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(null);

        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome Completo :");
        getContentPane().add(lblNome);
        lblNome.setBounds(10, 10, 100, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(30, 40, 270, 40);

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail :");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 80, 50, 40);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(30, 110, 270, 40);

        lblSenha.setBackground(new java.awt.Color(255, 255, 255));
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha :");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(10, 160, 50, 40);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(30, 200, 170, 40);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(50, 260, 90, 40);

        btnAgoraNao.setText("Agora não");
        btnAgoraNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgoraNaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgoraNao);
        btnAgoraNao.setBounds(180, 260, 90, 40);

        lblJaPossuiConta.setForeground(new java.awt.Color(255, 255, 255));
        lblJaPossuiConta.setText("Já possui conta ? ");
        getContentPane().add(lblJaPossuiConta);
        lblJaPossuiConta.setBounds(70, 340, 100, 30);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(180, 330, 75, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicial/aa.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 777, 450);

        setSize(new java.awt.Dimension(564, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/petshop", "root", "elizabete");
            PreparedStatement st = conectado.prepareStatement("INSERT INTO cadastrar VALUES(?,?,?)");
            st.setString(1, (txtEmail.getText()));
            st.setString(2, txtNome.getText());
            st.setString(3, txtSenha.getText());
            st.executeUpdate(); //executa o insert
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
            //Limpa os Campos
            //btnExcluir.setVisible(true);
            txtEmail.setText("");
            txtNome.setText("");
            txtSenha.setText("");
            //Posiciona o cursor dentro do campo usuário 
            txtEmail.requestFocus();
        } catch (ClassNotFoundException x) {
            JOptionPane.showMessageDialog(null, "Driver JDBC não encontrado " + x.getMessage());
        } catch (SQLException x) {
            if (x.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Este Usuário " + txtEmail.getText() + " já está cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados " + x.getMessage());
            }

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAgoraNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgoraNaoActionPerformed
        new Home().setVisible(true);
    }//GEN-LAST:event_btnAgoraNaoActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        new Logiin().setVisible(true);
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgoraNao;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblJaPossuiConta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
