/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicial;

/**
 *
 * @author eliza
 */
public class Contato extends javax.swing.JFrame {

    /**
     * Creates new form Contato
     */
    public Contato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblLocalizacao = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblFixo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicial/maps.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setTitle("Contato");
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(null);

        lblLocalizacao.setText("Localização:");
        getContentPane().add(lblLocalizacao);
        lblLocalizacao.setBounds(28, 24, 75, 16);

        lblEndereco.setText("Rua monteiro lobato, 30 , Jardim Adeus - Sorocaba");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(49, 66, 280, 16);

        lblContato.setText("Contato :");
        getContentPane().add(lblContato);
        lblContato.setBounds(30, 110, 60, 16);

        lblTelefone.setText("+55 19 985263789");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(60, 140, 100, 16);

        lblFixo.setText("+55 54896257");
        getContentPane().add(lblFixo);
        lblFixo.setBounds(60, 170, 100, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicial/maps.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 417, 1455, 670);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicial/maps.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 866));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 530, 170);

        setSize(new java.awt.Dimension(564, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFixo;
    private javax.swing.JLabel lblLocalizacao;
    private javax.swing.JLabel lblTelefone;
    // End of variables declaration//GEN-END:variables
}
