/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicial;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author eliza
 */
public class MuraldeFotos extends javax.swing.JFrame {

    /**
     * Creates new form MuraldeFotos
     */
    public MuraldeFotos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbGostei = new javax.swing.JComboBox<>();
        cmbAmei = new javax.swing.JComboBox<>();
        cmbNaoGostei = new javax.swing.JComboBox<>();
        lblFofura = new javax.swing.JLabel();
        btnAvaliar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mural de Fotos");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicial/roupas.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 200, 200);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicial/coelhos.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(260, 10, 230, 100);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicial/real.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 150, 210, 170);

        cmbGostei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gostei", "Não gostei" }));
        getContentPane().add(cmbGostei);
        cmbGostei.setBounds(50, 250, 120, 22);

        cmbAmei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gostei", "Não gostei" }));
        getContentPane().add(cmbAmei);
        cmbAmei.setBounds(320, 330, 130, 22);

        cmbNaoGostei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gostei", "Não gostei" }));
        cmbNaoGostei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNaoGosteiActionPerformed(evt);
            }
        });
        getContentPane().add(cmbNaoGostei);
        cmbNaoGostei.setBounds(320, 120, 130, 22);

        lblFofura.setText("Cuidado fofura abaixo:");
        getContentPane().add(lblFofura);
        lblFofura.setBounds(10, 10, 130, 16);

        btnAvaliar.setText("Avaliar");
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvaliar);
        btnAvaliar.setBounds(140, 320, 72, 23);

        setBounds(0, 0, 564, 407);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNaoGosteiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNaoGosteiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNaoGosteiActionPerformed

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/petshop", "root", "elizabete");
            PreparedStatement st = conectado.prepareStatement("INSERT INTO avaliacao VALUES(?,?,?)");
            st.setString(1, cmbGostei.getSelectedItem().toString());
            st.setString(2, cmbNaoGostei.getSelectedItem().toString());
            st.setString(3, cmbAmei.getSelectedItem().toString());
            st.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Avaliação realizada com sucesso");
            cmbGostei.setSelectedIndex(0);
            cmbNaoGostei.setSelectedIndex(0);
            cmbAmei.setSelectedIndex(0);
            cmbGostei.requestFocus(); 
        } catch (ClassNotFoundException x) { 
            JOptionPane.showMessageDialog(null, "Driver JDBC não encontrado " + x.getMessage());
        } catch (SQLException x) {
            if (x.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Avaliação " + cmbGostei.getSelectedItem().toString() + " já realizada");
            } else {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados " + x.getMessage());
            }
        }
    }//GEN-LAST:event_btnAvaliarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JComboBox<String> cmbAmei;
    private javax.swing.JComboBox<String> cmbGostei;
    private javax.swing.JComboBox<String> cmbNaoGostei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFofura;
    // End of variables declaration//GEN-END:variables
}
